### ISSUE TITLE
View specific ERC20 token balance.

### ISSUE THREAD

**Issue by verifiedly** [renproject/send-crypto#35]
Is It possible to view the balance of a specific ERC20 token? For example, if I send USDC to an ETH address, is It possible to see the USDC balance ?

**Comment by 0x31** [comment]
See `getBalance` and `getBalanceInSats`. For ERC20s, the first parameter is the token details and the second optional parameter can specify an address.

For example, to get the balance of the address "0xd8da6bf...":

```
const CryptoAccount = require("send-crypto");
const account = new CryptoAccount(process.env.PRIVATE_KEY);

await account.getBalance({
    type: "ERC20",
    address: "0x408e41876cccdc0f92210600ef50372656052a38",
}, {
    // Account to get balance of - or remove to get balance of `account`.
    address: "0xd8da6bf26964af9d7eed9e03e53415d37aa96045"
});
```
