### ISSUE TITLE
Fees problem

### ISSUE THREAD

**Issue by GeavaPapi** [renproject/send-crypto#48]
How can I fix the problem with fees/taxes on ETH 
When I'm trying to send a transaction I get that I don't have enough balance to pay the fees

**Comment by 0x31** [comment]
ETH and ERC20 transfers will require additional ETH to pay the transaction gas cost. If you are trying to send an address's entire balance, you can direct it to automatically subtract the gas fee from the transfer amount with the `subtractFee` parameter:

```ts
const CryptoAccount = require("send-crypto");
const account = new CryptoAccount(process.env.PRIVATE_KEY);

const balance = await account.getBalance("ETH");
await account.send("0x05a56e2d52c817161883f50c441c3228cfe54d9f", balance, "ETH", {
    subtractFee: true,
});
```

**Comment by GeavaPapi** [comment]
and for btc?

**Comment by GeavaPapi** [comment]
also, sometimes when im using this thing on btc im getting a error like the bot was not able toi include the fees, and i was having like 8$ in the wallet
